# Generated by Django 4.1.7 on 2023-04-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interface_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('mobile', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='电话号码')),
                ('email', models.EmailField(blank=True, default='', max_length=200, null=True, verbose_name='电子邮件')),
                ('createUser', models.CharField(blank=True, max_length=200, null=True, verbose_name='创建人')),
                ('createTime', models.DateTimeField(auto_now_add=True, max_length=100, null=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('yn', models.CharField(blank='是否有效', choices=[('YES', '是'), ('NO', '否')], max_length=100)),
            ],
        ),
    ]
