# Generated by Django 4.1.7 on 2023-04-20 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='interface_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestType', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=50, verbose_name='请求方式')),
                ('interfaceName', models.CharField(max_length=100, verbose_name='接口名称')),
                ('interfaceAddress', models.CharField(max_length=1024, verbose_name='接口地址')),
                ('status', models.CharField(blank=True, choices=[('effective', '有效'), ('invalid', '无效')], max_length=200, null=True, verbose_name='状态')),
                ('executeNumber', models.IntegerField(blank=True, null=True, verbose_name='执行次数')),
                ('ownerCase', models.CharField(blank=True, max_length=200, null=True, verbose_name='所属用例')),
                ('yn', models.CharField(blank='是否有效', choices=[('YES', '是'), ('NO', '否')], max_length=100)),
                ('createUser', models.CharField(max_length=200, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=200, verbose_name='修改人')),
                ('createTime', models.DateTimeField(auto_now_add=True, max_length=100, null=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('requestParameterType', models.CharField(blank=True, choices=[('form-data', '表单(form-data)'), ('raw', '源数据(raw)'), ('x-www-form-urlencoded', 'x-www-form-urlencoded')], max_length=50, null=True, verbose_name='请求参数格式')),
            ],
            options={
                'verbose_name': '接口',
                'verbose_name_plural': '接口管理',
                'ordering': ['-updateTime'],
            },
        ),
        migrations.CreateModel(
            name='interface_businessCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=500, null=True, verbose_name='业务名称')),
                ('createUser', models.CharField(max_length=200, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=200, verbose_name='修改人')),
                ('createTime', models.DateTimeField(auto_now_add=True, max_length=100, null=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('yn', models.CharField(blank='是否有效', choices=[('YES', '是'), ('NO', '否')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='interfaceRunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(verbose_name='响应结果')),
                ('header', models.TextField(verbose_name='响应header')),
                ('statusCode', models.IntegerField(verbose_name='状态码')),
                ('assertResult', models.CharField(max_length=20, null=True, verbose_name='断言结果')),
                ('interfaceapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.interface_base', verbose_name='所属接口')),
            ],
        ),
        migrations.AddField(
            model_name='interface_base',
            name='businessCategories',
            field=models.ManyToManyField(to='myapp.interface_businesscategories', verbose_name="业务分类'"),
        ),
        migrations.CreateModel(
            name='ApiParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApiHead', models.CharField(blank=True, max_length=1024, null=True, verbose_name='head内容')),
                ('format', models.CharField(blank=True, max_length=1024, null=True, verbose_name='请求参数格式')),
                ('request_value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='参数内容')),
                ('_type', models.CharField(choices=[('Int', 'Int'), ('String', 'String')], default='String', max_length=1024, verbose_name='参数类型')),
                ('required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('raw_data', models.TextField(blank=True, null=True, verbose_name='raw内容')),
                ('expected_result', models.TextField(blank=True, null=True, verbose_name='预期结果')),
                ('api', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.interface_base', verbose_name='所属接口')),
            ],
        ),
    ]
