# Generated by Django 4.1.7 on 2023-04-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_interface_base_interface_businesscategories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_businesscategories',
            name='yn',
            field=models.CharField(blank='是否有效', choices=[('YES', '是'), ('NO', '否')], max_length=100, verbose_name='是否有效'),
        ),
    ]
