# Generated by Django 4.1.7 on 2023-04-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_interface_businesscategories_yn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_businesscategories',
            name='yn',
            field=models.CharField(blank='是否有效', choices=[(1, '是'), (2, '否')], default=1, max_length=100, verbose_name='是否有效'),
        ),
    ]
