# Generated by Django 4.1.7 on 2023-04-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_interface_businesscategories_yn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_businesscategories',
            name='updateUser',
            field=models.CharField(max_length=200, null=True, verbose_name='修改人'),
        ),
    ]
