# Generated by Django 4.0.1 on 2023-05-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_interface_businesscategories_updateuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_base',
            name='businessCategories',
            field=models.ManyToManyField(to='myapp.interface_businessCategories', verbose_name="业务分类'"),
        ),
    ]
